-- =============================================================================
-- 0001_rls_and_seed.sql
-- Hand-written. Runs after 0000_schema.sql (generated by drizzle-kit).
-- Enables RLS, defines policies, and seeds the exercise library on user signup.
-- =============================================================================

-- 1. Enable RLS on every user-owned table.
alter table public.user_preferences  enable row level security;
alter table public.exercises          enable row level security;
alter table public.routines           enable row level security;
alter table public.routine_exercises  enable row level security;
alter table public.sessions           enable row level security;
alter table public.sets               enable row level security;

-- 2. Policies. Same pattern for every table:
--    user can SELECT/INSERT/UPDATE/DELETE only rows where user_id = auth.uid().
do $$
declare
  t text;
  tables text[] := array[
    'user_preferences', 'exercises', 'routines',
    'routine_exercises', 'sessions', 'sets'
  ];
begin
  foreach t in array tables loop
    execute format($f$
      drop policy if exists %1$I_select on public.%1$I;
      create policy %1$I_select on public.%1$I
        for select using (auth.uid() = user_id);

      drop policy if exists %1$I_insert on public.%1$I;
      create policy %1$I_insert on public.%1$I
        for insert with check (auth.uid() = user_id);

      drop policy if exists %1$I_update on public.%1$I;
      create policy %1$I_update on public.%1$I
        for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

      drop policy if exists %1$I_delete on public.%1$I;
      create policy %1$I_delete on public.%1$I
        for delete using (auth.uid() = user_id);
    $f$, t);
  end loop;
end $$;

-- 3. Seed function — populates a fresh user with default preferences and a
--    starter exercise library on first sign-up.
create or replace function public.seed_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_preferences (user_id, weight_unit)
  values (new.id, 'kg')
  on conflict (user_id) do nothing;

  insert into public.exercises (user_id, name, primary_muscle, equipment)
  values
    (new.id, 'Back Squat',         'quadriceps', 'barbell'),
    (new.id, 'Front Squat',        'quadriceps', 'barbell'),
    (new.id, 'Deadlift',           'hamstrings', 'barbell'),
    (new.id, 'Romanian Deadlift',  'hamstrings', 'barbell'),
    (new.id, 'Bench Press',        'chest',      'barbell'),
    (new.id, 'Incline Bench Press','chest',      'barbell'),
    (new.id, 'Overhead Press',     'shoulders',  'barbell'),
    (new.id, 'Barbell Row',        'back',       'barbell'),
    (new.id, 'Pendlay Row',        'back',       'barbell'),
    (new.id, 'Pull-up',            'back',       'bodyweight'),
    (new.id, 'Chin-up',            'back',       'bodyweight'),
    (new.id, 'Dip',                'chest',      'bodyweight'),
    (new.id, 'Push-up',            'chest',      'bodyweight'),
    (new.id, 'Lat Pulldown',       'back',       'cable'),
    (new.id, 'Seated Cable Row',   'back',       'cable'),
    (new.id, 'Face Pull',          'shoulders',  'cable'),
    (new.id, 'Cable Tricep Pushdown','triceps',  'cable'),
    (new.id, 'Bicep Curl',         'biceps',     'dumbbell'),
    (new.id, 'Hammer Curl',        'biceps',     'dumbbell'),
    (new.id, 'Lateral Raise',      'shoulders',  'dumbbell'),
    (new.id, 'Rear Delt Fly',      'shoulders',  'dumbbell'),
    (new.id, 'Dumbbell Bench Press','chest',     'dumbbell'),
    (new.id, 'Dumbbell Row',       'back',       'dumbbell'),
    (new.id, 'Goblet Squat',       'quadriceps', 'dumbbell'),
    (new.id, 'Bulgarian Split Squat','quadriceps','dumbbell'),
    (new.id, 'Leg Press',          'quadriceps', 'machine'),
    (new.id, 'Leg Curl',           'hamstrings', 'machine'),
    (new.id, 'Leg Extension',      'quadriceps', 'machine'),
    (new.id, 'Calf Raise',         'calves',     'machine'),
    (new.id, 'Plank',              'core',       'bodyweight'),
    (new.id, 'Hanging Leg Raise',  'core',       'bodyweight');

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.seed_new_user();

-- 4. Helper: keep updated_at fresh on every UPDATE.
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

do $$
declare
  t text;
  tables text[] := array[
    'user_preferences', 'exercises', 'routines',
    'routine_exercises', 'sessions', 'sets'
  ];
begin
  foreach t in array tables loop
    execute format($f$
      drop trigger if exists %1$I_touch_updated_at on public.%1$I;
      create trigger %1$I_touch_updated_at
        before update on public.%1$I
        for each row execute function public.touch_updated_at();
    $f$, t);
  end loop;
end $$;
